export const recipe = [
    {
        id: '1',
        title: 'Deep Fried Jalapeno Poppers',
        day: "Sunday's dish",
        tagline: "Some peppers always get jalapeno face don't they?",
        ingredients: [
            "1 pound jalapeños",
            "1 pound (16 ounces) cream cheese",
            "2 tablespoons fresh juice from 2 limes",
            "1/2 teaspoon garlic powder",
            "1/2 teaspoon onion powder",
            "Kosher salt",
            "2 cups whole milk",
            "2 cups all-purpose flour",
            "2 cups fine breadcrumbs",
            "1 to 2 quarts vegetable or canola oil, for frying",
            "1 batch of roasted tomato salsa or your favorite salsa, for serving"
        ],
        preparation: [
            "Wearing gloves if you have them, trim off and discard the top and bottom of each jalapeño. Cut each jalapeño crosswise into 1-inch rings. Remove seeds and white inner ribs from each ring (a small melon-baller works well for this).",
            "In a medium mixing bowl, stir cream cheese with lime juice, garlic powder, onion powder, and cumin until thoroughly blended. Season with salt. Using a butter knife, pack cream cheese into each jalapeño ring, filling it completely and smoothing the surface.",
            "Fill 1 bowl with milk, 1 bowl with flour, and 1 bowl with breadcrumbs. Working 1 popper at a time, dip in milk, then transfer to flour.",
            "Coat popper in flour all over. Transfer to a parchment-lined baking sheet and repeat with remaining poppers. Let floured poppers stand for 5 minutes.",
            "Working 1 popper at a time, return floured popper to milk, turning to coat. Transfer to breadcrumbs.",
            "Pack popper in breadcrumbs, turning to coat, until an even coating has formed. Repeat with remaining poppers.",
            "Heat 2 inches of oil to 350°F. Add poppers and fry, gently turning and stirring, until golden brown, about 5 minutes. Transfer to a paper towel-lined baking sheet and season with salt. Let stand 5 minutes before serving with salsa.",
        ],
        liked: false,
        duration: "25 mins",
        img: require("../assets/icons/Deep-Fried-Jalapeno-Poppers.jpg")
    },
    {
        id: '2',
        title: 'Cheesy Foam Tea',
        day: "Monday's dish",
        tagline: 'Pure quali-tea mate.',
        liked: false,
        duration: "15 mins",
        img: require("../assets/icons/Cheesy-Foam-Tea.jpg"),
        ingredients: [
            "200 ml UHT Whipping Cream",
            "200 g Cream Cheese (any brands would do, best is Philadelphia)",
            "100 ml Fresh Milk (Full Cream or Whole Milk)",
            "1 tsp Salt (sea salt)",
            "100 g Sugar",
        ],
        preparation: [
            "With a clean mixing bowl, mash cream cheese into smaller pieces.",
            "Add sugar and salt into cream cheese and beat until sugar dissolves.",
            "Slowly introduce milk into cheese batter and continue whisking.",
            "Whisk until cheese batter is foamy and set aside.",
            "With a separated mixing bowl, whisk whipping cream.",
            "Whisk whipping cream until medium peak consistency.",
            "Mix medium peak cream into cheese batter and whisk.",
            "Whisk until foamy then keep in the refrigerator.",
            "Serving with any beverage of your preference.",
            "Scoop the cheese batter on top of the beverage.",
        ],
    },
    {
        id: '3',
        title: 'Mac-n-Cheese Waffles ',
        day: "Tuesday's dish",
        tagline: 'Cheesy puns are waffle.\n But they mac me happy :)',
        liked: false,
        duration: "35 mins",
        img: require("../assets/icons/Mac-n-Cheese-Waffles.jpg"),
        ingredients: [
            "1 pound dried macaroni",
            "Kosher salt",
            "2 tablespoons butter, plus more for greasing baking sheet",
            "1 tablespoon flour",
            "1 cups whole milk",
            "Dash hot sauce, plus more for serving",
            "1 teaspoon mustard",
            "1 1/4 pounds grated cheddar cheese",
            "Maple syrup for serving of course.",
        ],
        preparation: [
            "Place pasta in a large pot and cover with lukewarm water by 2 inches. Add 2 tablespoons salt. Bring to a boil over high heat, stirring occasionally, and cook until pasta is tender, about 6 minutes after coming to a boil. Drain pasta.",
            "While pasta cooks, heat butter in a large Dutch oven over medium heat until melted. Add flour and cook, stirring, until pale golden blond. Slowly whisk in whole milk. Whisk in hot sauce and mustard. Bring to a simmer. Reduce heat to low and stir in 3/4 pounds grated cheese. Stir until melted.",
            "When pasta is cooked, add cheese sauce and stir to combine. Pour mixture into a greased rimmed baking sheet and flatten with a spatula. Refrigerate until completely set, about 30 minutes.",
            "Preheat a waffle iron. Carefully cut macaroni and cheese into 8 even squares.",
            "Using a wide spatula, carefully lift one square and plate it on a cutting board. Cover top with 1/4 of remaining cheese. Place another square of macaroni on top of cheese, creating a sandwich.",
            "Place sandwich in waffle maker. Close and cook until golden brown on both sides and cheese has crisped up, about 6 minutes. Remove from waffle iron and serve with syrup and hot sauce. Repeat steps 4 through 6 for remaining waffles.",
        ],
    },
    {
        id: '4',
        title: 'Four Cheese Pizza',
        day: "Wednesday's dish",
        tagline: "Try me and you'll always have a pizza my heart.",
        liked: false,
        duration: "1 hr 30 mins",
        img: require("../assets/icons/Four-Cheese-Deep-Dish-Pizza.jpg"),
        ingredients: [
            "1 recipe Basic Pizza Dough or 1 pound prepared pizza dough, at room temperature",
            "Nonstick cooking spray",
            "2 tablespoon olive oil",
            "4 cloves garlic, coarsely chopped",
            "6 ounce fresh baby spinach",
            "1 cup shredded mozzarella cheese (4 ounces)",
            "½ cup shredded provolone cheese (2 ounces)",
            "½ cup shredded Asiago cheese (2 ounces)",
            "¾ cup ricotta cheese",
            "2 tablespoon toasted pine nuts",
        ],
        preparation: [
            "Prepare a basic pizza dough.Preheat oven to 500°F. Coat a 14-inch pizza pan with cooking spray; set aside.",
            "In a medium nonstick skillet heat 1 tablespoon of the oil over medium-high heat. Add garlic; cook and stir for 30 seconds. Gradually add spinach; cook about 2 minutes or just until wilted. Remove from heat.",
            "On a lightly floured surface, roll dough into a 14-inch circle. Transfer to the prepared pizza pan.",
            "In a medium bowl combine mozzarella, provolone, and Asiago cheeses. Sprinkle half of the cheese mixture over dough. Top with spinach; drizzle any oil and garlic remaining in skillet over spinach. Sprinkle with the remaining cheese mixture. Top with spoonfuls of ricotta cheese; drizzle with the remaining 1 tablespoon oil.",
            "Bake for 14 to 15 minutes or until crust is brown on the bottom. Sprinkle with pine nuts.",
        ]
    },
    {
        id: '5',
        title: 'Limoncello Cheesecake Bars',
        day: "Thursday's dish",
        tagline: 'Try this and see your dreams crumb true.',
        liked: false,
        duration: "4 hrs",
        img: require("../assets/icons/Limoncello-Cheesecake-Bars.png"),
        ingredients: [
            "2 cup graham cracker crumbs",
            "¼ cup sugar",
            "2 teaspoon lemon zest",
            "½ cup butter, melted",
            "2 8 ounce packages cream cheese, softened",
            "⅔ cup sugar",
            "2 teaspoon vanilla",
            "½ cup limoncello (Italian lemon liqueur)",
            "2 eggs",
            "Candied lemon slices",
        ],
        preparation: [
            "Preheat oven to 350°F. Line a 13×9-inch baking pan with foil, extending foil over edges. In a medium bowl stir together graham cracker crumbs, the 1/4 cup sugar, and the lemon zest. Add melted butter; stir until combined. Spread in prepared pan; press firmly. Bake 8 minutes or until lightly browned.",
            "In a large bowl beat cream cheese, the 2/3 cup sugar, and the vanilla with a mixer on medium until combined. Beat in limoncello until smooth. Beat in eggs just until combined. Pour filling over baked crust. Bake 20 minutes or until set. Let cool in pan on a wire rack 1 hour. Chill at least 2 hours.",
            "Using foil, lift out uncut bars. Cut into bars. Top with Candied Lemon Slices. If desired, dust with powdered sugar. Refrigerate up to 3 days. Makes 24 bars.",
        ],
    },
    {
        id: '6',
        title: 'Tomato-n-Grilled Cheese Soup',
        day: "Friday's dish",
        tagline: 'Love you from my head tomatoes',
        liked: false,
        duration: "35 mins",
        img: require("../assets/icons/Tomato-n-Grilled-Cheese-Soup.png"),
        ingredients: [
            "Olive oil",
            "1 onion, diced",
            "1 teapsoon Italian seasoning",
            "¼ teaspoon black pepper",
            "¼ teaspoons red pepper flakes",
            "Pinch salt",
            "6 large cloves garlic",
            "3 ounces (½ can) tomato paste",
            "1 (28 ounce) can whole, San Marzano-style tomatoes",
            "1 ounce fresh basil leaves",
            "¼ heaping cup flat-leaf parsley",
            "1 tablespoon sugar",
            "4 cups chicken stock, hot",
            "½ cup grated parmesan cheese",
            "French baguette, sliced into about 12 (½”) slices",
            "1 small clove garlic, peeled but whole",
            "1 – 1 ½ cups shredded, Italian-style 4 Cheese blend",
        ],
        preparation: [
            "Place a soup pot over medium-high heat, and add in about 3-4 tablespoons of olive oil; once hot, add in the diced onion and saute for few minutes until the onion begins to slightly brown.",
            "Add in Italian seasoning, the black pepper, the red pepper flakes and a pinch of salt, and stir to combine; add in the garlic, and stir that in to incorporate.",
            "Once the garlic become aromatic (about 30 seconds or so), add in the tomato paste and allow it cook for a minute or so to cook out the raw flavor; then, add in the canned tomatoes, the fresh basil and parsley, and the sugar, and stir to combine.",
            "Add in the chicken stock, and then simmer the soup, partially covered, for 20 minutes.",
            "After the 20 minutes, turn off the heat and add in the grated parmesan, and stir; then, using a hand-held immersion blender (or even your blender, but work in batches!), puree the soup until completely smooth; check the seasoning to see if any additional salt/pepper is needed.",
            "Make some garlic toasts by drizzling some oil over the baguette slices, then placing them onto a baking sheet and under the broiler just until golden and toasty; then, rub the clove of garlic over each slice and add a pinch of salt. (You can leave your broiler on for the next step.)",
            "To assemble your bowls, ladle some soup into oven-safe bowls, and top each with about 2-3 garlic toasts; then, sprinkle on about ¼ cup (or more) of the cheese, and place under the broiler to melt and become bubbly; carefully remove and garnish with a sprinkle of parsley before serving.",
        ],
    },
    {
        id: '7',
        title: 'Smashed Peach Grilled Cheese',
        day: "Saturday's dish",
        tagline: 'Will leave you completely speachless',
        liked: false,
        duration: "15 mins",
        img: require("../assets/icons/Smashed-Peach-Grilled-Cheese.png"),
        ingredients: [
            "2 medium peaches, halved and pitted",
            "½ teaspoon ground ancho chile pepper (optional)",
            "4 slices sourdough bread",
            "3 ounce sliced sharp white cheddar cheese",
            "1 large fresh poblano pepper, roasted* and cut into strips",
            "4 slices bacon, crisp-cooked",
            "2 tablespoon softened butter",
        ],
        preparation: [
            "If desired, sprinkle cut sides of peach halves with ground chile. Using a potato masher or the flat side of a meat mallet, gently smash peach halves to 1/2-inch thickness.",
            "Top two bread slices with cheese slices. Add two peach halves, poblano strips, and bacon to each. Top with remaining bread slices. Butter both sides of each sandwich.",
            "Cook sandwiches in a hot skillet over medium 2 to 3 minutes or until toasted. Turn; repeat on other side until cheese melts. Makes 2 sandwiches.",
        ],
    },
];