export const fonts = {
    BLACK: 'Spartan-Black',
    // BOLD: 'Spartan-Bold',
    EXTRA_BOLD: 'Spartan-ExtraBold',
    EXTRA_LIGHT: 'Spartan-ExtraLight',
    LIGHT: 'Spartan-Light',
    MEDIUM: 'Spartan-Medium',
    // REGULAR: 'Spartan-Regular',
    SEMI_BOLD: 'Spartan-SemiBold',
    THIN: 'Spartan-Thin',
    BOLD: 'Montserrat-Bold',
    REGULAR: 'Montserrat-Regular',
    // BLACK: 'Montserrat-Black',
    EXTRA_BOLD: 'Montserrat-ExtraBold',
    // LIGHT: 'Montserrat-Light',
    // SEMI_BOLD: 'Montserrat-SemiBold',
    // THIN: 'Montserrat-Thin',
    // MEDIUM: 'Montserrat-Medium',
    ANTHONY: 'anthony-hunter',
    // PRO: 'Proxima-Nova-Font',
    // PRO_ALT_BOLD: 'Proxima-Nova-Alt-Bold',
    // PRO_BOLD: 'Proxima-Nova-Bold',
    // PRO_LIGHT: 'Proxima-Nova-Alt-Light',
    // PRO_THIN: 'Proxima-Nova-Alt-Thin',
    // PRO_BLACK: 'Proxima-Nova-Black',
    // PRO_EXTRA_BOLD: 'Proxima-Nova-Extrabold',
    // PRO_REGULAR: 'ProximaNova-Regular',
}